### ISSUE TITLE
Flex Flow SID

### ISSUE THREAD

**Issue by dchumpitaz** [twilio/flex-webchat-ui-sample#1]
Sorry, I review all my Flex cloud installation and I can't find the Flex Flow SID. I need it to run the sample.

```
var appConfig = {
    //  change the your AccountSid
    accountSid: "AC...",
    // change to your Flex Flow SID
    flexFlowSid: "FO...",
    colorTheme: {
        overrides: brandedColors
    }
}
```

Where I can find it?

**Comment by james-mallory** [comment]
@dchumpitaz I am also trying to figure out where to find this value. One way that seems like a workaround is as follows. As a side note my Flex project is still in the trial. You can find this value by opening the webchat demo from the admin view.

```
Go to https://flex.twilio.com/admin/dashboard
Click on the Launch button in the section where it says Test Drive
The flex flow sid is a URL parameter
```

I've also searched around in the console and can't find anywhere where this sid is mentioned.

**Comment by dchumpitaz** [comment]
@james-mallory thanks a lot!!! I will see the button.
Yes, my Flex project is in trial too. But, I'm very very very sure about that button is not visible since I setup the project (I delete a prior project and setup again). Well, the important is I can see the button and get the value.
I test the sample with the FO SID and works!!!
Thanks a lot again.

**Comment by dchumpitaz** [comment]
Closing the issue.

**Comment by jstallm** [comment]
I found it here https://flex.twilio.com/admin/developers

**Comment by HannaMerilynAaviksoo** [comment]
Found it here: https://www.youtube.com/watch?v=E2WlfZhuLKk (from 5.20)
