### ISSUE TITLE
Integration with redux store not possible 

### ISSUE THREAD

**Issue by dziamid** [twilio/flex-webchat-ui-sample#2]
Root reducer is not exported in flex-webchat-ui, wich makes it impossible to integrate with custom redux store.

**Comment by dziamid** [comment]
Is this project maintained?

**Comment by AdrianaPineda** [comment]
Hey @dziamid. Apologies for the late response.
You can use your custom redux store as of version 1.2.0. Check it out here: https://www.twilio.com/docs/flex/release-notes/webchat-ui-release-notes#added-3
