### ISSUE TITLE
Yarn not supported

### ISSUE THREAD

**Issue by hlascelles** [twilio/flex-webchat-ui-sample#8]
Should there be a note similar to this one about yarn not being supported? https://github.com/twilio/flex-plugin-builder/issues/2

**Comment by constmontague** [comment]
@dkundel is there any movement at Twilio to make some of these libraries `yarn` compatible?
It looks like `yarn` isn't going to handle `bundledDependencies` (even in Berry), and we would rather not rip out `yarn` just for one set of packages.

We're looking at building some stuff with Twilio Flex so this would be really big for us!

https://github.com/yarnpkg/yarn/issues/5998

**Comment by dkundel** [comment]
I think there are some plans with the engineering team to internally restructure some things that would make it compatible. I don't know about any timeline though.

**Comment by constmontague** [comment]
@dkundel Awesome to hear! Thanks for following up with the engineering team and with us

**Comment by kolencherry** [comment]
@constmontague @hlascelles [Support for yarn](https://www.twilio.com/changelog/flex-ui-119-support-yarn-now-available) has been released with flex-ui 1.19 and flex-webchat-ui 2.4. You can find docs for this at [the following page](https://github.com/twilio/flex-plugin-builder/tree/master/packages/create-flex-plugin#using-yarn). 

Thank you for your patience!

**Comment by constmontague** [comment]
@kolencherry @dkundel thanks very much! Looking forward to using it
